<?php

// Action to load scripts into the theme
add_action('wp_enqueue_scripts', 'theme_enqueue_styles');
function theme_enqueue_styles(){
    // Load style.css of parent theme
    wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
    // Load theme personalized css
    wp_enqueue_style('theme-style', get_stylesheet_directory_uri() . '/css/theme.css', array(), filemtime(get_stylesheet_directory() . '/css/theme.css'));
}

// suppression of HTML "p" tag generated by plugin contact form7
add_filter('wpcf7_autop_or_not', '__return_false');

// Add "Admin" item into header nav menu only when administrator user is logged in
add_filter( 'wp_nav_menu_items', 'add_extra_item_to_nav_menu', 10, 2 ); // priority=10 nb_arguments=2

function add_extra_item_to_nav_menu( $items, $args ) { // $items is a string containing HTML list of menu items. $args is an object containing wp_nav_menu() arguments

    if (is_user_logged_in() && is_super_admin() && $args->theme_location == 'primary') { // if admin user is logged and change applied to header menu only
       
        /* fill table with each items of the menu */
        while ( ( $item_pos = strpos ( $items, '<li', 1) ) !== false)
        {
            $items_array[] = substr($items, 0, $item_pos);
            $items = substr($items, $item_pos);
        }
        $items_array[] = $items;

        /* insert new item into table (keep argument#3=0) (adjust 2nd argument with position to insert) */
        array_splice($items_array, 1, 0, '<li><a href="'. home_url( '/wp-admin/index.php' ) .'">Admin</a></li>'); 

        /* transform table into string */
        $items = implode('', $items_array);
    }

    return $items;
}
